//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCADAEntities : DbContext
    {
        public SCADAEntities()
            : base("name=SCADAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INF_Takt> INF_Takt { get; set; }
        public virtual DbSet<STA_Alarm> STA_Alarm { get; set; }
        public virtual DbSet<INF_Scanned> INF_Scanned { get; set; }
    }
}
