//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_Takt
    {
        public int ID { get; set; }
        public string StationSN { get; set; }
        public System.DateTime RecordFristEnteredTime { get; set; }
        public Nullable<System.DateTime> RecordLastEnteredTime { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public Nullable<int> RecordWorkSeconds { get; set; }
        public Nullable<int> RecordWaitSeconds { get; set; }
    }
}
